server:
  port: 20004
spring:
  boot:
    admin:
      client:
        url: "http://localhost:20001/"
        username: admin
        password: admin
  application:
    name: fund-service
  security:
    user:
      name: admin
      password: admin
      roles: ACTUATOR_ADMIN
  devtools:
    livereload:
      port: 35731
      enabled: true

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: fund-service
    path: ./logs
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false