
eureka:
  server:
    disable-delta: true
    registry-sync-retries: 0
    registry-sync-retry-wait-ms: 0
    rate-limiter-registry-fetch-average-rate: 500  #??????????????????????
    remote-region-registry-fetch-interval: 5000
    batch-replication: true
    rate-limiter-burst-size: 10 #???????
    rate-limiter-enabled: true #???????????
    rate-limiter-full-fetch-average-rate: 100 #????????
    rate-limiter-throttle-standard-clients: false #??????client????????????false???????client????
    enable-self-preservation: true #???????????
    eviction-interval-timer-in-ms: 60000 #????????????????????60*1000??60?
    delta-retention-timer-interval-in-ms: 60000  #???????????? delta ??
    renewal-percent-threshold: 0.85 #?????????????client???????
    renewal-threshold-update-interval-ms: 60000 #???????????
    response-cache-auto-expiration-in-seconds: 180 #????????????????
    response-cache-update-interval-ms: 180000 #??????????????????
    sync-when-timestamp-differs: true #?????????????????
    use-read-only-response-cache: true #???????????????????????????
  client:
    register-with-eureka: false  #???????? Eureka-Server ?????? true
    fetch-registry: false
    filter-only-up-instances: true
    eureka-connection-idle-timeout-seconds: 30
    eureka-server-connect-timeout-seconds: 30 #client??eureka??????????????5?
    eureka-server-read-timeout-seconds: 30 #client??????????
    allow-redirects: false #?????????????????????? ?????false?????????????????true??????HTTP???????????false
    disable-delta: false
    cache-refresh-executor-exponential-back-off-bound: 10
    cache-refresh-executor-thread-pool-size: 2 #??????????????????2
    eureka-server-total-connections: 200
    eureka-service-url-poll-interval-seconds: 180
    g-zip-content: true
    healthcheck:
      enabled: true
    heartbeat-executor-thread-pool-size: 2
    heartbeat-executor-exponential-back-off-bound: 10
    initial-instance-info-replication-interval-seconds: 40
    instance-info-replication-interval-seconds: 60
    log-delta-diff: false
    on-demand-update-status-change: true
    prefer-same-zone-eureka: true
    refresh:
      enable: true
    region: "us-east-1"
    registry-fetch-interval-seconds: 15
    should-enforce-registration-at-init: false #??????????????????????
    should-unregister-on-shutdown: true
    webclient:
      enabled: false
    tls:
      enabled: false
  instance:
    app-group-name: server
    appname: server
    namespace: eureka
    prefer-ip-address: false
server:
  port: 20004
debug: true
